src/Entity/Film.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
#[Vich\Uploadable]

class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre_francais = null;

    #[ORM\Column(length: 255)]
    private ?string $titre_original = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $affiche = null;

    #[Vich\UploadableField(mapping: 'films', fileNameProperty: 'affiche')]
    private ?File $imageFile = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $duree = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $synopsis = null;

    #[ORM\Column(length: 255)]
    private ?string $pays_origine = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_sortie_france = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_sortie_pays_origine = null;

    // #[ORM\Column(length: 255, nullable: true)]
    // private ?string $bandes_annonces_teasers = null;

    // #[Vich\UploadableField(mapping: 'films', fileNameProperty: 'bandes_annonces_teasers')]
    // private ?File $imageFile2 = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: Article::class)]
    private Collection $article;

    #[ORM\ManyToOne(inversedBy: 'film')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Categorie $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'film')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Forum $forum = null;

    #[ORM\ManyToMany(targetEntity: Genre::class, mappedBy: 'film')]
    private Collection $genres;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: Critique::class)]
    private Collection $critiques;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: Notation::class)]
    private Collection $notations;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'realisateurs_films')]
    #[JoinTable(name: 'realisateurs_artistes')]
    private Collection $realisateur;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'producteurs_films')]
    #[JoinTable(name: 'producteurs_artistes')]
    private Collection $producteur;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'scenaristes_films')]
    #[JoinTable(name: 'scenaristes_artistes')]
    private Collection $scenariste;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'casting_film')]
    #[JoinTable(name: 'casting_artiste')]
    private Collection $casting;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'compositeurs_films')]
    #[JoinTable(name: 'compositeurs_artistes')]
    private Collection $compositeur;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'films')]
    private Collection $artistes;

    #[ORM\ManyToOne(inversedBy: 'films')]
    private ?Langue $langue = null;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: BandesAnnoncesTeasers::class, orphanRemoval: true, cascade:['persist', 'remove'])]
    private Collection $bandesAnnoncesTeasers;

    public function __construct()
    {
        $this->article = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->critiques = new ArrayCollection();
        $this->notations = new ArrayCollection();
        $this->realisateur = new ArrayCollection();
        $this->producteur = new ArrayCollection();
        $this->scenariste = new ArrayCollection();
        $this->casting = new ArrayCollection();
        $this->compositeur = new ArrayCollection();
        $this->artistes = new ArrayCollection();
        $this->bandesAnnoncesTeasers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString()
    {
        return $this->titre_francais;
    }

    public function getTitreFrancais(): ?string
    {
        return $this->titre_francais;
    }

    public function setTitreFrancais(string $titre_francais): static
    {
        $this->titre_francais = $titre_francais;

        return $this;
    }

    public function getTitreOriginal(): ?string
    {
        return $this->titre_original;
    }

    public function setTitreOriginal(string $titre_original): static
    {
        $this->titre_original = $titre_original;

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche = null): static
    {
        $this->affiche = $affiche;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): static
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getPaysOrigine(): ?string
    {
        return $this->pays_origine;
    }

    public function setPaysOrigine(string $pays_origine): static
    {
        $this->pays_origine = $pays_origine;

        return $this;
    }

    public function getDateSortieFrance(): ?\DateTimeInterface
    {
        return $this->date_sortie_france;
    }

    public function setDateSortieFrance(\DateTimeInterface $date_sortie_france): static
    {
        $this->date_sortie_france = $date_sortie_france;

        return $this;
    }

    public function getDateSortiePaysOrigine(): ?\DateTimeInterface
    {
        return $this->date_sortie_pays_origine;
    }

    public function setDateSortiePaysOrigine(\DateTimeInterface $date_sortie_pays_origine): static
    {
        $this->date_sortie_pays_origine = $date_sortie_pays_origine;

        return $this;
    }




    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticle(): Collection
    {
        return $this->article;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->article->contains($article)) {
            $this->article->add($article);
            $article->setFilm($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->article->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getFilm() === $this) {
                $article->setFilm(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getForum(): ?Forum
    {
        return $this->forum;
    }

    public function setForum(?Forum $forum): static
    {
        $this->forum = $forum;

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): static
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
            $genre->addFilm($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): static
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeFilm($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Critique>
     */
    public function getCritiques(): Collection
    {
        return $this->critiques;
    }

    public function addCritique(Critique $critique): static
    {
        if (!$this->critiques->contains($critique)) {
            $this->critiques->add($critique);
            $critique->setFilm($this);
        }

        return $this;
    }

    public function removeCritique(Critique $critique): static
    {
        if ($this->critiques->removeElement($critique)) {
            // set the owning side to null (unless already changed)
            if ($critique->getFilm() === $this) {
                $critique->setFilm(null);
            }
        }

        return $this;
    }

    /**

src/Form/SearchType.php
<?php

namespace App\Form;

use App\Entity\Search;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('search', TextType::class, [
                    'attr' => [
                        'placeholder' => 'Recherche via un mot clé...',
                        'class' => 'custom-placeholder'
                    ],
                    'row_attr' => ['class' => 'mx-5 my-3'],
                ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Search::class,
            'method' => 'GET',
            'csrf_protection' => false
        ]);
    }
}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Entity\Search;
use App\Form\SearchType;
use App\Repository\FilmRepository;
use App\Repository\AlbumRepository;
use App\Repository\LivreRepository;
use App\Repository\SerieRepository;
use App\Repository\ArtisteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/search')]
class SearchController extends AbstractController
{

    #[Route('/', name: 'app_search_index', methods: ['GET'])]
    public function index(Request $request, ArtisteRepository $artisteRepository, FilmRepository $filmRepository, SerieRepository $serieRepository, AlbumRepository $albumRepository, LivreRepository $livreRepository): Response
    {
        $search = new Search();
        $form = $this->createForm(SearchType::class, $search);

        // Gérez la soumission du formulaire
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérez les paramètres de recherche
            // $type = $search->getType();
            // $terme = $search->getTerme();

            // En fonction du type de recherche, exécutez la recherche appropriée

            $artistes = $artisteRepository->findBySearch($search);

            $livres = $livreRepository->findBySearch($search);

            $films = $filmRepository->findBySearch($search);

            $series = $serieRepository->findBySearch($search);

            $albums = $albumRepository->findBySearch($search);

            return $this->render('search/index.html.twig', [
                'artistes' => $artistes,
                'livres' => $livres,
                'films' => $films,
                'series' => $series,
                'albums' => $albums,
            ]);

            // dd($artistes, $films, $livres, $albums, $series);
            // Type de recherche non pris en charge

            // La méthode array_merge permet de concaténer les tableaux.
        }

        // Affichez le formulaire de recherche vide
        return $this->render('search/_form.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function renderSearchForm(){
        $search = new Search();
        $form = $this->createForm(SearchType::class, $search, [
            'action' => $this->generateUrl('app_search_index')
        ]);
        
        return $this->render('search/_form.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    
    // #[Route('/front', name: 'app_search_global', methods: ['GET'])]
    // public function search(SearchRepository $searchRepository, Request $request, ArtisteRepository $artisteRepository, FilmRepository $filmRepository, SerieRepository $serieRepository, AlbumRepository $albumRepository, LivreRepository $livreRepository): Response
    // {
    //     $search = new Search();
    //     $form = $this->createForm(SearchType::class, $search);

    //     $searchTerm = $request->query->get('search_term');

    //     $form->handleRequest($request);

    //     $artistes = [];
    //     $livres = [];
    //     $films = [];
    //     $series = [];
    //     $albums = [];

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         // Récupérez les paramètres de recherche
    //         // $type = $search->getType();
    //         // $terme = $search->getTerme();

    //         // En fonction du type de recherche, exécutez la recherche appropriée

    //         $artistes = $artisteRepository->findBySearch($search);

    //         $livres = $livreRepository->findBySearch($search);

    //         $films = $filmRepository->findBySearch($search);

    //         $series = $serieRepository->findBySearch($search);

    //         $albums = $albumRepository->findBySearch($search);

    //         // dd($artistes, $films, $livres, $albums, $series);
    //         // Type de recherche non pris en charge

    //         // La méthode array_merge permet de concaténer les tableaux.
    //     }

    //     return $this->render('front/index.html.twig', [
    //         'form' => $form->createView(),
    //         'searchTerm' => $searchTerm,
    //         'artistes' => $artistes,
    //         'livres' => $livres,
    //         'films' => $films,
    //         'series' => $series,
    //         'albums' => $albums,
    //         'searches' => $searchRepository->findAll(),
    //     ]);
    // }

    #[Route('/new', name: 'app_search_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $search = new Search();
        $form = $this->createForm(SearchType::class, $search);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($search);
            $entityManager->flush();

            return $this->redirectToRoute('app_search_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('search/new.html.twig', [
            'search' => $search,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_search_show', methods: ['GET'])]
    public function show(Search $search): Response
    {
        return $this->render('search/show.html.twig', [
            'search' => $search,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_search_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Search $search, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SearchType::class, $search);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_search_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('search/edit.html.twig', [
            'search' => $search,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_search_delete', methods: ['POST'])]
    public function delete(Request $request, Search $search, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $search->getId(), $request->request->get('_token'))) {
            $entityManager->remove($search);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_search_index', [], Response::HTTP_SEE_OTHER);
    }

    // public function search()
    // {
    //     // Créez une instance de la classe Recherche et associez-la à RechercheType



    // }
}

templates/search/_delete_form.html.twig
<form method="post" action="{{ path('app_search_delete', {'id': search.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ search.id) }}">
    <button class="btn">Delete</button>
</form>

templates/search/_form.html.twig
{{ form_start(form) }}

<div class="search-bar input-group">

			{{form_widget(form.search)}}

			<button class="btn-svg btn inline-block px-6 py-2.5 bg-blue-600 text-black font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center" type="submit" id="button-addon2">
				<svg xmlns="http://www.w3.org/2000/svg" width="30" height="15" viewbox="0 0 512 512"><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128c0-70.7 57.2-128 128-128c70.7 0 128 57.2 128 128c0 70.7-57.2 128-128 128z"/></svg>
			</button>

</div>

{{ form_end(form) }}

templates/search/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Search{% endblock %}

{% block body %}
    <h1>Edit Search</h1>

    {{ include('search/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_search_index') }}">back to list</a>

    {{ include('search/_delete_form.html.twig') }}
{% endblock %}

templates/search/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search index
{% endblock %}

{% block body %}
	<div class="h1-résultats-search h1-search">
		<h1>Résultats de la recherche :</h1>
	</div>

	{% block content %}
		{% if artistes | length > 0 or livres | length > 0 or films | length > 0 or series | length > 0 or albums | length > 0 %}
			<div class="search-artiste">
				{% if artistes | length > 0 %}
					<div class="h3-search-artiste">
						<h3>Artistes</h3>
					</div>
					<ul>
						{% for artiste in artistes %}
							<div class="ul-search-artiste">
								<div class="search-artiste-item1">
									<div>
										<a href="{{ path('app_admin_artiste_show', {'id': artiste.id}) }}" class="a-artiste-nom">
											<li><img class="search-artiste-photo" src="{{ vich_uploader_asset(artiste, 'imageFile') }}" alt="Couverture du livre"></li>
										</a>
									</div>
								</div>
								<div class="search-artiste-item2">
									<div>
										<a href="{{ path('app_admin_artiste_show', {'id': artiste.id}) }}" class="a-artiste-nom">
											<li class="search-artiste-nom">
												<b>Nom :</b>
												{{ artiste.nom }}
											</li>
										</a>
									</div>
									<div>
										<li class="search-artiste-date-naissance">
											<b>Date de naissance :</b>
											{{ artiste.dateNaissance ? "Le "  ~ artiste.dateNaissance|format_datetime(locale='fr',pattern="dd MMMM YYYY") : '' }}
										</li>
									</div>
									<div>
										<li class="search-artiste-activite">
											<b>Activité(s) :</b>
											{% for metiers in artiste.metiers %}
												{{ metiers.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-artiste-ville">
											<b>Ville d'origine :</b>
											{{artiste.ville.nom}}
										</li>
									</div>
									<div>
										<li class="search-artiste-pays">
											<b>Pays d'origine :</b>
											{{ artiste.paysOrigine }}
										</li>
									</div>
								</div>
								<div class="search-artiste-item3">
									<li class="search-artiste-presentation">
										<p>
											<b>Présentation :</b>
										</p>
										{{ artiste.presentation }}
									</li>
								</div>
							</div>
						{% endfor %}
					</ul>
				{% endif %}
			</div>

			<div class="search-livre">
				{% if livres | length > 0 %}
					<div class="h3-search-livre">
						<h3>Livres</h3>
					</div>
					<ul>
						{% for livre in livres %}
							<div class="ul-search-livre">
								<div class="search-livre-item1">
									<div>
										<a href="{{ path('app_admin_livre_show', {'id': livre.id}) }}" class="a-livre-titre">
											<li><img class="search-livre-couverture" src="{{ vich_uploader_asset(livre, 'imageFile') }}" alt="Couverture du livre"></li>
										</a>
									</div>
								</div>
								<div class="search-livre-item2">
									<div>
										<a href="{{ path('app_admin_livre_show', {'id': livre.id}) }}" class="a-livre-titre">
											<li class="search-livre-titre">
												<b>Titre français :</b>
												<i>{{ livre.titreFrancais }}</i>
											</li>
										</a>
									</div>
									<div>
										<li class="search-livre-auteur">
											<b>Auteur(s) :</b>
											{% for artiste in livre.auteur %}
												{{ artiste.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-livre-genre">
											<b>Genre(s) :</b>
											{% for Genre in livre.Genres %}
												{{ Genre.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-livre-editeur">
											<b>Editeur(s) :</b>
											{% for EditeurFrance in livre.EditeurFrance %}
												{{ EditeurFrance.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-livre-date">
											<b>Parution :</b>
											{% set formattedDate = livre.DatePublicationFrance ? "Le " ~ livre.DatePublicationFrance|format_datetime(locale='fr',pattern="dd MMMM YYYY") : '' %}{{ formattedDate }}
										</li>
									</div>
								</div>
								<div class="search-livre-item3">
									<li class="search-livre-synopsis">
										<p>
											<b>Synposis :</b>
										</p>
										{{ livre.synopsis }}
									</li>
								</div>
							</div>
						{% endfor %}
					</ul>
				{% endif %}
			</div>

			<div class="search-film">
				{% if films | length > 0 %}
					<div class="h3-search-film">
						<h3>Films</h3>
					</div>
					<ul>
						{% for film in films %}
							<div class="ul-search-film">
								<div class="search-film-item1">
									<div>
										<a href="{{ path('app_admin_film_show', {'id': film.id}) }}" class="a-film-titre">
											<li><img class="search-film-affiche" src="{{ vich_uploader_asset(film, 'imageFile') }}" alt="Affiche du film"></li>
										</a>
									</div>
								</div>
								<div class="search-film-item2">
									<div>
										<a href="{{ path('app_admin_film_show', {'id': film.id}) }}" class="a-film-titre">
											<li class="search-film-titre">
												<b>Titre français :</b>
												<i>{{ film.titreFrancais }}</i>
											</li>
										</a>
									</div>
									<div>
										<li class="search-film-realisateur">
											<b>Réalisateur(s) :</b>
											{% for artiste in film.realisateur %}
												{{ artiste.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-film-genre">
											<b>Genre(s) :</b>
											{% for Genre in film.Genres %}
												{{ Genre.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-film-duree">
											<b>Durée :</b>
											{{ film.duree ? film.duree|date('H') ~ 'h' ~ film.duree|date('i') : '' }}
										</li>
									</div>
									<div>
										<li class="search-film-date">
											<b>Sortie :</b>
											{{ film.dateSortieFrance ? "Le " ~ film.dateSortieFrance|format_datetime(locale='fr',pattern="dd MMMM YYYY") : '' }}</li>
									</div>
								</div>
								<div class="search-film-item3">
									<li class="search-film-synopsis">
										<p>
											<b>Synposis :</b>
										</p>
										{{ film.synopsis }}</li>
								</div>
							</div>
						{% endfor %}
					</ul>
				{% endif %}
			</div>

			<div class="search-serie">
				{% if series | length > 0 %}
					<div class="h3-search-serie">
						<h3>Séries</h3>
					</div>
					<ul>
						{% for serie in series %}
							<div class="ul-search-serie">
								<div class="search-serie-item1">
									<div>
										<a href="{{ path('app_admin_serie_show', {'id': serie.id}) }}" class="a-serie-titre">
											<li><img class="search-serie-affiche" src="{{ vich_uploader_asset(serie, 'imageFile') }}" alt="Affiche du film"></li>
										</a>
									</div>
								</div>
								<div class="search-serie-item2">
									<div>
										<a href="{{ path('app_admin_serie_show', {'id': serie.id}) }}" class="a-serie-titre">
											<li class="search-serie-titre">

												<b>Titre français :</b>
												<i>{{ serie.titreFrancais }}</i>
											</li>
										</a>
									</div>
									<div>
										<li class="search-serie-createur">
											<b>Créateur(s) :</b>
											{% for artiste in serie.createur %}
												{{ artiste.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-serie-genre">
											<b>Genre(s) :</b>
											{% for Genre in serie.Genres %}
												{{ Genre.nom }}
											{% endfor %}
										</li>
									</div>
									<div>
										<li class="search-serie-duree">
											<b>Durée :</b>
											{{ serie.duree ? serie.duree|date('H') ~ 'h' ~ serie.duree|date('i') : '' }}
										</li>
									</div>
									<div>
										<li class="search-serie-date">
											<b>Sortie :</b>
											{{ serie.dateDiffusionFrance ? "Le "  ~ serie.dateDiffusionFrance|format_datetime(locale='fr',pattern="dd MMMM YYYY") : '' }}</li>
									</div>
								</div>
								<div class="search-serie-item3">
									<li class="search-serie-synopsis">
										<p>
											<b>Synposis :</b>
										</p>
										{{ serie.synopsis }}</li>
								</div>
							</div>
						{% endfor %}
					</ul>
				{% endif %}
			</div>

			{% if albums | length > 0 %}
				<h3>Albums</h3>
				<ul>
					{% for album in albums %}
						<li>
							<a href="{{ path('app_admin_album_show', {'id': album.id}) }}">
								{{ album.titreFrancais }}</a>
						</li>
					{% endfor %}
				</ul>
			{% endif %}

		{% else %}
			<div class="h1-résultats-search h1-search">
				<h3>Aucun résultat trouvé</h3>
			</div>
		{% endif %}
	{% endblock %}
{% endblock %}

templates/search/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Search{% endblock %}

{% block body %}
    <h1>Create new Search</h1>

    {{ include('search/_form.html.twig') }}

    <a href="{{ path('app_search_index') }}">back to list</a>
{% endblock %}

templates/search/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search{% endblock %}

{% block body %}
    <h1>Search</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ search.id }}</td>
            </tr>
            <tr>
                <th>Search</th>
                <td>{{ search.search }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_search_index') }}">back to list</a>

    <a href="{{ path('app_search_edit', {'id': search.id}) }}">edit</a>

    {{ include('search/_delete_form.html.twig') }}
{% endblock %}