src/Entity/Film.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
#[Vich\Uploadable]

class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre_francais = null;

    #[ORM\Column(length: 255)]
    private ?string $titre_original = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $affiche = null;

    #[Vich\UploadableField(mapping: 'films', fileNameProperty: 'affiche')]
    private ?File $imageFile = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $duree = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $synopsis = null;

    #[ORM\Column(length: 255)]
    private ?string $pays_origine = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_sortie_france = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_sortie_pays_origine = null;

    // #[ORM\Column(length: 255, nullable: true)]
    // private ?string $bandes_annonces_teasers = null;

    // #[Vich\UploadableField(mapping: 'films', fileNameProperty: 'bandes_annonces_teasers')]
    // private ?File $imageFile2 = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: Article::class)]
    private Collection $article;

    #[ORM\ManyToOne(inversedBy: 'film')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Categorie $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'film')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Forum $forum = null;

    #[ORM\ManyToMany(targetEntity: Genre::class, mappedBy: 'film')]
    private Collection $genres;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: Critique::class)]
    private Collection $critiques;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: Notation::class)]
    private Collection $notations;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'realisateurs_films')]
    #[JoinTable(name: 'realisateurs_artistes')]
    private Collection $realisateur;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'producteurs_films')]
    #[JoinTable(name: 'producteurs_artistes')]
    private Collection $producteur;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'scenaristes_films')]
    #[JoinTable(name: 'scenaristes_artistes')]
    private Collection $scenariste;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'casting_film')]
    #[JoinTable(name: 'casting_artiste')]
    private Collection $casting;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'compositeurs_films')]
    #[JoinTable(name: 'compositeurs_artistes')]
    private Collection $compositeur;

    #[ORM\ManyToMany(targetEntity: Artiste::class, inversedBy: 'films')]
    private Collection $artistes;

    #[ORM\ManyToOne(inversedBy: 'films')]
    private ?Langue $langue = null;

    #[ORM\OneToMany(mappedBy: 'film', targetEntity: BandesAnnoncesTeasers::class, orphanRemoval: true, cascade:['persist', 'remove'])]
    private Collection $bandesAnnoncesTeasers;

    public function __construct()
    {
        $this->article = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->critiques = new ArrayCollection();
        $this->notations = new ArrayCollection();
        $this->realisateur = new ArrayCollection();
        $this->producteur = new ArrayCollection();
        $this->scenariste = new ArrayCollection();
        $this->casting = new ArrayCollection();
        $this->compositeur = new ArrayCollection();
        $this->artistes = new ArrayCollection();
        $this->bandesAnnoncesTeasers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString()
    {
        return $this->titre_francais;
    }

    public function getTitreFrancais(): ?string
    {
        return $this->titre_francais;
    }

    public function setTitreFrancais(string $titre_francais): static
    {
        $this->titre_francais = $titre_francais;

        return $this;
    }

    public function getTitreOriginal(): ?string
    {
        return $this->titre_original;
    }

    public function setTitreOriginal(string $titre_original): static
    {
        $this->titre_original = $titre_original;

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche = null): static
    {
        $this->affiche = $affiche;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): static
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getPaysOrigine(): ?string
    {
        return $this->pays_origine;
    }

    public function setPaysOrigine(string $pays_origine): static
    {
        $this->pays_origine = $pays_origine;

        return $this;
    }

    public function getDateSortieFrance(): ?\DateTimeInterface
    {
        return $this->date_sortie_france;
    }

    public function setDateSortieFrance(\DateTimeInterface $date_sortie_france): static
    {
        $this->date_sortie_france = $date_sortie_france;

        return $this;
    }

    public function getDateSortiePaysOrigine(): ?\DateTimeInterface
    {
        return $this->date_sortie_pays_origine;
    }

    public function setDateSortiePaysOrigine(\DateTimeInterface $date_sortie_pays_origine): static
    {
        $this->date_sortie_pays_origine = $date_sortie_pays_origine;

        return $this;
    }




    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticle(): Collection
    {
        return $this->article;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->article->contains($article)) {
            $this->article->add($article);
            $article->setFilm($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->article->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getFilm() === $this) {
                $article->setFilm(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getForum(): ?Forum
    {
        return $this->forum;
    }

    public function setForum(?Forum $forum): static
    {
        $this->forum = $forum;

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): static
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
            $genre->addFilm($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): static
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeFilm($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Critique>
     */
    public function getCritiques(): Collection
    {
        return $this->critiques;
    }

    public function addCritique(Critique $critique): static
    {
        if (!$this->critiques->contains($critique)) {
            $this->critiques->add($critique);
            $critique->setFilm($this);
        }

        return $this;
    }

    public function removeCritique(Critique $critique): static
    {
        if ($this->critiques->removeElement($critique)) {
            // set the owning side to null (unless already changed)
            if ($critique->getFilm() === $this) {
                $critique->setFilm(null);
            }
        }

        return $this;
    }

    /**

src/Controller/AdminLivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Entity\Search;
use App\Form\LivreType;
use App\Form\SearchType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/livre')]
class AdminLivreController extends AbstractController
{
    #[Route('/', name: 'app_admin_livre_index', methods: ['GET'])]
    public function index(LivreRepository $livreRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $search = new Search();
        $form = $this->createForm(SearchType::class, $search);

        $form -> handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $search->getPage($request -> query -> getInt('page', 1));

            $pagination = $paginator->paginate(
                $livreRepository -> findBySearch($search), /* query NOT result */
                $request->query->getInt('livre', 1), /*page number*/
                10,  /*limit per page*/
                ["pageParameterName" => "livre"]
            );

            return $this->render('admin_livre/index.html.twig', [
                'form' => $form->createView(),
                'livres' => $pagination
            ]);
        }

        $pagination = $paginator->paginate(
            $livreRepository -> findAll(), /* query NOT result */
            $request->query->getInt('livre', 1), /*page number*/
            10,  /*limit per page*/
            ["pageParameterName" => "livre"]
        );

        return $this->render('admin_livre/index.html.twig', [
            'form' => $form->createView(),
            'livres' => $pagination
        ]);
    }

    #[Route('/new', name: 'app_admin_livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('admin_livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_livre/_delete_form.html.twig
<div class="fiche-modifier-supprimer my-2 rounded text-center">
	<form method="post" action="{{ path('app_admin_livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
		<button class="btn-fiche-modifier-supprimer rounded text-center text-white fw-bold">Supprimer</button>
	</form>
</div>

templates/admin_livre/_form.html.twig
{# {{ form_start(form) }}

    <div class="flex justify-center">
	<div class="mb-3 xl:w-96">
		<div class="input-group relative flex flex-wrap items-stretch w-full mb-4">

			{{form_widget(form.search)}}

			<button class="btn inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center" type="submit" id="button-addon2">
				<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512">
					<path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
				</svg>
			</button>
		</div>
	</div>
</div>
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

{{ form_start(form) }}

{{form_row(form.titre_francais)}}
{{form_row(form.titre_original)}}
{{form_row(form.auteur)}}
{{form_row(form.imageFile)}}
{{form_row(form.genres)}}
{{form_row(form.synopsis)}}
{{form_row(form.pays_origine)}}
{{form_row(form.date_publication_france)}}
{{form_row(form.date_publication_pays_origine)}}

<p class="mx-5 my-3 fw-bold">Version originale</p>

{{form_row(form.langue)}}
{{form_row(form.editeur_pays_origine)}}
{{form_row(form.ISBN)}}

<p class="mx-5 my-3 fw-bold">Version française</p>

{{form_row(form.traducteur)}}
{{form_row(form.editeur_france)}}
{{form_row(form.ISBN_france)}}
{{form_row(form.forum)}}

<button class="btn-ajouter-livre form-control mx-5 my-3 btn fw-bold">{{ button_label|default('Ajouter le livre') }}</button>

{{ form_end(form) }}

templates/admin_livre/_search_data_html.twig
{{form_start(form)}}
<div class="search flex justify-center input-group relative flex flex-wrap items-stretch w-full mb-4 mb-3 xl:w-50">

	{{form_widget(form.search)}}

	<button class="btn-svg btn inline-block px-6 py-2.5 bg-blue-600 text-black font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center" type="submit" id="button-addon2">
		<svg xmlns="http://www.w3.org/2000/svg" width="30" height="15" viewbox="0 0 512 512"><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128c0-70.7 57.2-128 128-128c70.7 0 128 57.2 128 128c0 70.7-57.2 128-128 128z"/></svg>

	</button>
</div>
{{form_end(form)}}

templates/admin_livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <h1>Edit Livre</h1>

    {{ include('admin_livre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_livre_index') }}">back to list</a>

    {{ include('admin_livre/_delete_form.html.twig') }}
{% endblock %}

templates/admin_livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin - Gestion des livres
{% endblock %}

{% block body %}

	<div class="h1-livres rounded text-center">
		<div class="item-h1-livres-fontawsome1"><i class="fa-solid fa-lock fa-3x"></i></div>
		<div class="item-h1-livres-fontawsome2"><h1>Admin - Gestion des livres</h1></div>
	</div>

	<div class="flex-container-livres1">
		<div>
			<span class="span-livres">Résultats :</span>
			{{ livres.getTotalItemCount }}</div>
		<div>{{ include('admin_livre/_search_data_html.twig') }}</div>
	</div>

	<div class="flex-container-livres2">
		<div class="ajouter my-2 rounded text-center">
			<a href="{{ path('app_admin_livre_new') }}" class="text-decoration-none text-white fw-bold">Ajouter</a>
		</div>
		<div></div>
	</div>

	<table class="table table-responsive table-stripped rounded">
		<thead>
			<tr class="rounded">
				<th class="rounded-row1">ID</th>
				<th>Titre francais</th>
				<th>Auteur(s)</th>
				<th>Genre(s)</th>
				<th class="rounded-row2">Actions</th>
			</tr>
		</thead>

		<tbody>

			{% for livre in livres %}
				<tr class="rounded">
					<td class="rounded-row1">{{ livre.id }}</td>
					<td>{{ livre.titreFrancais }}</td>

					<td>
						{% if livre.auteur %}
							{% for artiste in livre.auteur %}
								{{ artiste.nom }}
							{% endfor %}
						{% else %}
							<span class="text-danger fst-italic">N.R</span>
						{% endif %}
					</td>

					<td>
						{% if livre.Genres %}
							{% for Genre in livre.Genres %}
								{{ Genre.nom }}
							{% endfor %}
						{% else %}
							<span class="text-danger fst-italic">N.R</span>
						{% endif %}
					</td>

					<td class="rounded-row2">
						<div class="fiche-modifier-supprimer">
							<button class="btn-fiche-modifier-supprimer my-2 rounded text-center">
								<a href="{{ path('app_admin_livre_show', {'id': livre.id}) }}" class="text-decoration-none text-white fw-bold">Fiche</a>
							</button>
							<button class="btn-fiche-modifier-supprimer my-2 rounded text-center">
								<a href="{{ path('app_admin_livre_edit', {'id': livre.id}) }}" class="text-decoration-none text-white fw-bold">Modifier</a>
							</button>
							{{ include('admin_livre/_delete_form.html.twig') }}
						</div>
					</td>
				</tr>

			{% else %}
				<tr>
					<td colspan="10" class="rounded">Aucun résultat trouvé.</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<div class="navigation">
		{{ knp_pagination_render(livres) }}
	</div>
{% endblock %}

templates/admin_livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau livre
{% endblock %}

{% block body %}

	<div class="h1-ajouter-livre rounded text-center mx-5 my-3">
		<h1>Ajouter un livre</h1>
	</div>

	<div class="div-retour-liste-livres mx-5 my-3 rounded text-center">
		<a href="{{ path('app_admin_livre_index') }}" class="text-decoration-none text-white fw-bold">Retour à la liste des livres</a>
	</div>

	{{ include('admin_livre/_form.html.twig') }}
{% endblock %}

templates/admin_livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre
{% endblock %}

{% block body %}
	<h1>Livre</h1>

	<table class="table table-responsive table-stripped">
		<tbody>

			<tr>
				<th class="th-show-livre">Id</th>
				<td>{{ livre.id }}</td>
			</tr>

			<tr>
				<th>Titre français</th>
				<td>{{ livre.titreFrancais }}</td>
			</tr>

			<tr>
				<th class="th-show-livre">Titre original</th>
				<td>
					{% if livre.paysOrigine is same as ('France') %}
						<p>-</p>
					{% else %}
						{{ livre.titreOriginal }}
					{% endif %}
				</td>
			</tr>

			<tr>
				<th class="th-show-livre">Auteur(s)</th>
				<td>
					{% if livre.auteur %}
						{% for artiste in livre.auteur %}
							{{ artiste.nom }}
						{% endfor %}
					{% else %}
						<span class="text-danger fst-italic">N.R</span>
					{% endif %}
				</td>
			</tr>

			<tr>
				<th class="th-show-livre">Couverture</th>
				<td><img src="{{ vich_uploader_asset(livre, 'imageFile') }}" alt="Couverture du livre"></td>
			</tr>

			<tr>
				<th class="th-show-livre">Genre(s)</th>
				<td>
					{% if livre.Genres %}

						{% for Genre in livre.Genres %}
							{{ Genre.nom }}
						{% endfor %}
					{% endif %}
				</td>
			</tr>
		</tbody>
	</td>
</tr>

<tr>
	<th class="th-show-livre">Synopsis</th>
	<td>{{ livre.synopsis }}</td>
</tr>

<tr>
	<th>Pays d'origine</th>
	<td>{{ livre.PaysOrigine }}</td>
</tr>

<tr>
	<th class="th-show-livre">Date de publication (France)</th>
	<td>{% set formattedDate = livre.DatePublicationFrance ? "Le " ~ livre.DatePublicationFrance|date('d F Y', null, 'fr') : '' %}{% set translatedMonth = formattedDate|replace({'F': 'F'|trans}) %}
		{{ translatedMonth }}
	</td>
</tr>

<tr>
	<th class="th-show-livre">Date de publication (Pays d'origine)</th>
	<td>

		{% if livre.PaysOrigine is same as ('France') %}
			<p>-</p>
		{% else %}
			{% set formattedDate = livre.DatePublicationPaysOrigine ? "Le " ~ livre.DatePublicationPaysOrigine|date('d F Y', null, 'fr') : '' %}{{ formattedDate }}

		{% endif %}
	</td>

</tr></tbody></table><h3>Version originale</h3><table class="table"><tbody>

<tr>
	<th class="th-show-livre">Langue d'origine</th>
	<td>
		{% if livre.langue %}
			{{livre.langue.nom}}
		{% else %}
			<span class="text-danger fst-italic">N.R</span>
		{% endif %}
	</td>
</tr>

<tr>
	<th class="th-show-livre">Editeur(s)</th>
	<td>
		{% for EditeurPaysOrigine in livre.EditeurPaysOrigine %}
			{{ EditeurPaysOrigine.nom }}
		{% endfor %}
	</td>
</tr>

<tr>
	<th class="th-show-livre">ISBN</th>
	<td>{{ livre.ISBN }}</td>
</tr></tbody></table><h3>Version française</h3><table class="table"><tbody>

<tr>
	<th class="th-show-livre">Traducteur(s)</th>
	<td>
		{% if livre.langue.nom is same as ('Français') %}
			<p>-</p>
		{% else %}
			{% for traducteur in livre.traducteur %}
				{{ traducteur.nom }}
			{% endfor %}
		{% endif %}
	</td>
</tr>

<tr>
	<th class="th-show-livre">Editeur(s)</th>
	<td>

		{% if livre.langue.nom is same as ('Français') %}
			<p>-</p>
		{% else %}
			{% for EditeurFrance in livre.EditeurFrance %}
				{{ EditeurFrance.nom }}
			{% endfor %}
		{% endif %}

	</td>
</tr>

<tr>
	<th class="th-show-livre">ISBN</th>
	<td>
		{% if livre.langue.nom is same as ('Français') %}
			<p>-</p>
		{% else %}
			{{ livre.ISBNFrance }}
		{% endif %}
	</td>

</tr></tbody></table><a href="{{ path('app_admin_livre_index') }}">back to list</a><a href="{{ path('app_admin_livre_edit', {'id': livre.id}) }}">edit</a>{{ include('admin_livre/_delete_form.html.twig') }}{% endblock %}